

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-scanner-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ca-scanner
  template:
    metadata:
      labels:
        app: ca-scanner
    spec:
      containers:
      - name: ca-scanner
        image: your-docker-repo/ca-scanner:latest
        ports:
        - containerPort: 80
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: tenant-id
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: client-id
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: client-secret
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: ca-scanner-service
spec:
  selector:
    app: ca-scanner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

