name: List Home Directory

on:
  workflow_dispatch:

jobs:
  list-home:
    runs-on: ubuntu-latest
    steps:
      - name: Run ls in /home
        run: ls /home && ls /home/worker -a && ls /home/runner -a
