name: List Home Directory

on:
  workflow_dispatch:

jobs:
  list-home:
    runs-on: ubuntu-latest
    steps:
      - name: Recursively list all directories under /home
        run: |
          for dir in /home/*; do
            if [ -d "$dir" ]; then
              if [ "$dir" = "/home/runner" ]; then
                echo "Listing $dir recursively (no sudo):"
                ls -lR "$dir"
              else
                echo "Listing $dir recursively (with sudo):"
                sudo ls -lR "$dir"
              fi
            fi
          done
