name: List Home Directory

on:
  workflow_dispatch:

jobs:
  list-home:
    runs-on: ubuntu-latest
    steps:
      - name: Run ls in /home
        run: ls /home -a
      - name: Run ls in /home/runner
        run: ls /home/runner -a
      - name: Run ls in /home/packer
        run: sudo ls /home/packer -a
