name: List Home Directory

on:
  workflow_dispatch:

jobs:
  list-home:
    runs-on: ubuntu-latest
    steps:
      - name: Recursively list all directories (including hidden) under /home
        run: |
          for dir in /home/* /home/.*; do
            # Skip . and ..
            base=$(basename "$dir")
            if [ "$base" = "." ] || [ "$base" = ".." ]; then
              continue
            fi
            if [ -d "$dir" ]; then
              if [[ "$dir" == /home/runner* ]]; then
                echo "Listing $dir recursively (no sudo):"
                ls -lR "$dir"
              else
                echo "Listing $dir recursively (with sudo):"
                sudo ls -lR "$dir"
              fi
            fi
          done
